# Generated by Django 3.2.10 on 2022-01-29 10:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.PositiveIntegerField(default=0)),
                ('i_type', models.CharField(choices=[('deposit', 'Deposit'), ('bond', 'Bond'), ('found', 'Found')], default='deposit', max_length=100)),
                ('interval', models.IntegerField(default=0)),
                ('amount', models.IntegerField(default=0)),
                ('percent', models.DecimalField(decimal_places=1, default=0, max_digits=3)),
                ('man', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
