# Generated by Django 3.2.10 on 2021-12-28 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('button', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='button',
            name='addition',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='button',
            name='amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='button',
            name='interval',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='button',
            name='percent',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3),
        ),
        migrations.AddField(
            model_name='button',
            name='tax',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3),
        ),
    ]
