# Generated by Django 3.2.10 on 2022-01-29 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('button', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investment',
            name='man',
        ),
    ]
