# Generated by Django 3.2.10 on 2022-01-29 11:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('button', '0002_remove_investment_man'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investment',
            name='account',
        ),
        migrations.AddField(
            model_name='investment',
            name='investor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Investor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.PositiveIntegerField(default=0)),
                ('total_invest', models.PositiveIntegerField(default=0)),
                ('profit', models.PositiveIntegerField(default=0)),
                ('investor', models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
