# Generated by Django 3.2.10 on 2022-01-29 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('button', '0003_auto_20220129_1421'),
    ]

    operations = [
        migrations.AddField(
            model_name='investment',
            name='back',
            field=models.IntegerField(default=0),
        ),
    ]
