# Generated by Django 3.2.10 on 2022-01-29 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('button', '0004_investment_back'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investment',
            name='back',
        ),
    ]
