# Generated by Django 3.2.10 on 2022-02-05 13:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('button', '0005_remove_investment_back'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investor',
            name='id',
        ),
        migrations.AddField(
            model_name='investment',
            name='back',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='investment',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='investment',
            name='amount',
            field=models.IntegerField(default=0, verbose_name='Сумма'),
        ),
        migrations.AlterField(
            model_name='investment',
            name='i_type',
            field=models.CharField(choices=[('deposit', 'Deposit'), ('bond', 'Bond'), ('found', 'Found')], default='deposit', max_length=100, verbose_name='Вид'),
        ),
        migrations.AlterField(
            model_name='investment',
            name='interval',
            field=models.IntegerField(default=0, verbose_name='Период'),
        ),
        migrations.AlterField(
            model_name='investment',
            name='percent',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3, verbose_name='Процент'),
        ),
        migrations.AlterField(
            model_name='investor',
            name='investor',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
